import csv
import random
import os

# --- CONFIGURATION ---

# The input file generated by the cloning script.
# (Make sure this matches the output file from your last collect_repos run)
INPUT_CSV = os.path.join('..', 'data', 'raw', 'typescript_repos_metadata.csv')

# The output file where the random sample will be saved.
OUTPUT_CSV = os.path.join('..', 'data', 'processed', 'validation_log.csv')

# The number of samples to take from each group.
SAMPLE_SIZE = 25


# --- SCRIPT LOGIC ---

def create_validation_set():
    """
    Creates a stratified random sample from the collected repository data
    for manual validation.
    """
    repos_with_eslint = []
    repos_without_eslint = []

    # 1. Read the source data and stratify it into two groups.
    try:
        with open(INPUT_CSV, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row['has_eslint'] == 'True':
                    repos_with_eslint.append(row)
                else:
                    repos_without_eslint.append(row)
    except FileNotFoundError:
        print(f"ERROR: Input file not found. Make sure this file exists: {INPUT_CSV}")
        return

    print(f"Loaded {len(repos_with_eslint)} repositories with ESLint.")
    print(f"Loaded {len(repos_without_eslint)} repositories without ESLint.")

    # 2. Handle cases where a group has fewer than SAMPLE_SIZE repos.
    num_true_to_sample = min(SAMPLE_SIZE, len(repos_with_eslint))
    num_false_to_sample = min(SAMPLE_SIZE, len(repos_without_eslint))

    if num_true_to_sample < SAMPLE_SIZE:
        print(f"Warning: Found fewer than {SAMPLE_SIZE} repos with ESLint. Sampling all {num_true_to_sample}.")
    if num_false_to_sample < SAMPLE_SIZE:
        print(f"Warning: Found fewer than {SAMPLE_SIZE} repos without ESLint. Sampling all {num_false_to_sample}.")

    # 3. Perform the random sampling on each group.
    true_sample = random.sample(repos_with_eslint, num_true_to_sample)
    false_sample = random.sample(repos_without_eslint, num_false_to_sample)

    # 4. Combine the samples and shuffle them to randomize the order for manual checking.
    validation_sample = true_sample + false_sample
    random.shuffle(validation_sample)

    print("-" * 20)
    print(f"Created a validation sample of {len(validation_sample)} total repositories.")
    print(f"({num_true_to_sample} with ESLint, {num_false_to_sample} without ESLint)")
    print("-" * 20)

    # 5. Write the final sample to the output CSV file.
    output_headers = [
        'repo_full_name',
        'html_url',  # <-- ADDED
        'script_result_has_eslint',
        'script_result_path',
        'manual_check_eslint_found',
        'manual_check_path',
        'finding_type',
        'notes'
    ]

    os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)

    with open(OUTPUT_CSV, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(output_headers)

        for repo in validation_sample:
            writer.writerow([
                # Data from the original script's output
                repo['repo_full_name'],
                repo['html_url'],  # <-- ADDED
                repo['has_eslint'],
                repo['eslint_config_path'],
                # Blank columns for you to fill in manually
                '',  # manual_check_eslint_found
                '',  # manual_check_path
                '',  # finding_type
                ''   # notes
            ])

    print(f"Successfully created validation log file at: {OUTPUT_CSV}")


# --- EXECUTE THE SCRIPT ---
if __name__ == "__main__":
    create_validation_set()